doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App': '%kernel.project_dir%/migrations'
    enable_profiler: false
