# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'

teneleven_sylius_subscription_plugin_admin:
    resource: '@TenelevenSyliusSubscriptionPlugin/Resources/config/routing/admin.yml'
    prefix: /admin

teneleven_sylius_subscription_plugin_shop:
    resource: '@TenelevenSyliusSubscriptionPlugin/Resources/config/routing/shop.yml'
