# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

news:
    resource: 'routing/news.yml'
    
static_content:
    resource: 'routing/static_content.yml'
urbanara_catalog_plugin:
    resource: "@CatalogPromotionPlugin/Resources/config/routing.yml"
    prefix: /admin
    
sylius_shop_product_by_channel_and_taxonid:
    resource: 'routing/product_repository.yml'

sylius_order_restore:
    prefix: /admin
    resource: 'routing/restore_order.yml'
