winzou_state_machine:
    sylius_order:
        states:
            reopen: ~
        transitions:
            restore:
                from: [cancelled]
                to: reopen
            recancel:
                from: [reopen]
                to: cancelled
        callbacks:
            after:
                sylius_send_email:
                    on: ['new']
                    do: ["@app.email_manager.order_confirmation_admin", "sendOrderComfirmAdminkEmailManager"]
                    args: ["object"]
                sylius_restore_order_payment:
                    on: ['restore']
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'restore_payment'", "'sylius_order_payment'"]
                sylius_restore_order_shipping:
                    on: ['restore']
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'restore_shipment'", "'sylius_order_shipping'"]
                sylius_restore_payment:
                    on: ['restore']
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getPayments()", "event", "'restore_payment'", "'sylius_payment'"]
                sylius_restore_shipment:
                    on: ['restore']
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getShipments()", "event", "'restore_shipment'", "'sylius_shipment'"]                    
                sylius_restore_hold_inventory:
                    on: ["restore"]
                    do: ["@sylius.inventory.order_inventory_operator", "hold"]
                    args: ["object"]
                sylius_restore_increment_promotions_usages:
                    on: ["restore"]
                    do: ["@sylius.promotion_usage_modifier", "increment"]
                    args: ["object"]                    
                sylius_recancel_order_payment:
                    on: ["recancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'cancel'", "'sylius_order_payment'"]
                sylius_recancel_order_shipping:
                    on: ["recancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'cancel'", "'sylius_order_shipping'"]
                sylius_recancel_payment:
                    on: ["recancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getPayments()", "event", "'cancel'", "'sylius_payment'"]
                sylius_recancel_shipment:
                    on: ["recancel"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object.getShipments()", "event", "'cancel'", "'sylius_shipment'"]
                sylis_recancel_order:
                    on: ["recancel"]
                    do: ["@sylius.inventory.order_inventory_operator", "cancel"]
                    args: ["object"]
                sylius_recancel_decrement_promotions_usages:
                    on: ["recancel"]
                    do: ["@sylius.promotion_usage_modifier", "decrement"]
                    args: ["object"]                    
    sylius_order_shipping:
        transitions:
            restore_shipment:
                from: [cancelled]
                to: ready
    sylius_order_payment:
        transitions:
            restore_payment:
                from: [cancelled]
                to: awaiting_payment
    sylius_shipment:
        transitions:
            restore_shipment:
                from: [cancelled]
                to: ready
    sylius_payment:
        transitions:
            restore_payment:
                from: [cancelled]
                to: new