sylius_grid:
    grids:
        app_admin_static_content:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\StaticContent
            limits: [15, 30, 45, 100]
            fields:
                header:
                    type: string
                    label: app.ui.header
                    sortable: true
                    position: 0
                slug:
                    type: string
                    label: app.ui.slug
                    sortable: true
                    position: 1
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                header:
                    type: string
                    label: app.ui.header