name: Auto-merge

on:
    pull_request: ~

jobs:
    auto-merge:
        runs-on: ubuntu-18.04
        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Auto-merge minor dependencies upgrades
                uses: ahmadnassri/action-dependabot-auto-merge@v2
                with:
                    target: minor
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    config: .github/dependabot.yml
